import React, { useState } from 'react'
import { Download, FileImage, Loader2, Terminal } from 'lucide-react'
import { useSprite } from '../contexts/SpriteContext'
import { usePalette } from '../contexts/PaletteContext'
// @ts-ignore
import { GIFEncoder, quantize, applyPalette } from 'gifenc'

const ExportModal: React.FC<{ onClose: () => void }> = ({ onClose }) => {
  const { sprite, frames } = useSprite()
  const { resolveColor } = usePalette()
  const [isExportingGif, setIsExportingGif] = useState(false)
  const [isExportingBash, setIsExportingBash] = useState(false)

  const handleExportGif = async () => {
    setIsExportingGif(true)
    try {
      // Allow UI to update
      await new Promise(resolve => setTimeout(resolve, 50))
      
      const cellW = 20
      const cellH = 40
      const canvasWidth = sprite.width * cellW
      const canvasHeight = sprite.height * cellH

      const canvas = document.createElement('canvas')
      canvas.width = canvasWidth
      canvas.height = canvasHeight
      const ctx = canvas.getContext('2d', { willReadFrequently: true })
      if (!ctx) throw new Error('Could not get 2d context')

      const encoder = new GIFEncoder()
      
      for (let i = 0; i < frames.length; i++) {
        // Yield to prevent thread locking on large sprites
        await new Promise(resolve => setTimeout(resolve, 10))
        
        ctx.clearRect(0, 0, canvasWidth, canvasHeight)
        
        // Use default background color if no transparent
        const bg = resolveColor('base:bg')
        if (bg && bg !== 'transparent') {
          ctx.fillStyle = bg
          ctx.fillRect(0, 0, canvasWidth, canvasHeight)
        }
        
        sprite.draw(ctx, i, 0, 0, cellW, cellH, resolveColor)
        
        const imageData = ctx.getImageData(0, 0, canvasWidth, canvasHeight)
        const palette = quantize(imageData.data, 256, { format: 'rgba4444', clearAlpha: true })
        const index = applyPalette(imageData.data, palette)
        
        const transparentIndex = palette.findIndex((p: any) => p[3] === 0)
        const isTransparent = transparentIndex !== -1

        encoder.writeFrame(index, canvasWidth, canvasHeight, { 
          palette, 
          delay: 1000 / Math.max(1, sprite.fps),
          transparent: isTransparent,
          transparentIndex: isTransparent ? transparentIndex : undefined
        })
      }

      encoder.finish()
      const buffer = encoder.bytes()
      
      const path = await (window as any).api?.saveGif(buffer)
      if (path) {
        console.log('GIF Exported successfully:', path)
      }
    } catch (e) {
      console.error('Failed to export GIF', e)
      alert('Failed to export GIF')
    } finally {
      setIsExportingGif(false)
      onClose()
    }
  }

  const handleExportBash = async () => {
    setIsExportingBash(true)
    try {
      await new Promise(resolve => setTimeout(resolve, 50))
      
      let script = '#!/bin/bash\n\n'
      script += '# Generated by ASCII Sprite Editor\n\n'
      script += 'tput civis\n'
      script += 'clear\n'
      script += 'trap "tput cnorm; printf \'%b\\n\' \\"\\\\033[0m\\"; exit" SIGINT SIGTERM\n\n'
      
      script += 'while true; do\n'
      
      for (const frame of frames) {
        // Yield to prevent thread locking on massive scripts
        await new Promise(resolve => setTimeout(resolve, 10))
        
        script += '  printf \'%b\' "\\033[H"\n'
        for (let i = 0; i < sprite.height; i++) {
          let line = '  printf \'%b\\n\' "'
          for (let j = 0; j < sprite.width; j++) {
            const cell = frame[i][j]
            if (!cell || !cell.value) {
              line += ' '
              continue
            }
            
            const codes: string[] = []
            
            if (cell.fg_color === 'base:fg' || cell.fg_color === 'transparent') {
                codes.push('39')
            } else if (cell.fg_color.startsWith('ansi:')) {
                const ansiId = parseInt(cell.fg_color.split(':')[1])
                if (ansiId >= 0 && ansiId <= 7) codes.push((30 + ansiId).toString())
                else if (ansiId >= 8 && ansiId <= 15) codes.push((90 + ansiId - 8).toString())
            } else {
                codes.push('39')
            }
            
            if (cell.bg_color === 'base:bg' || cell.bg_color === 'transparent') {
                codes.push('49')
            } else if (cell.bg_color.startsWith('ansi:')) {
                const ansiId = parseInt(cell.bg_color.split(':')[1])
                if (ansiId >= 0 && ansiId <= 7) codes.push((40 + ansiId).toString())
                else if (ansiId >= 8 && ansiId <= 15) codes.push((100 + ansiId - 8).toString())
            } else {
                codes.push('49')
            }
            
            if (cell.weight === 'bold' || cell.weight === 'bright') codes.push('1')
            if (cell.italic) codes.push('3')
            if (cell.underline) codes.push('4')
            if (cell.blink) codes.push('5')
            if (cell.strike_through) codes.push('9')
            
            const charStr = cell.value || ' '
            let escapedChar = charStr.replace(/(["\\$`])/g, '\\\\$1')
            
            line += `\\\\033[${codes.join(';')}m${escapedChar}\\\\033[0m`
          }
          line += '"\n'
          script += line
        }
        script += `  sleep ${1 / Math.max(1, sprite.fps)}\n`
      }
      script += 'done\n'

      const path = await (window as any).api?.saveBash(script)
      if (path) {
        console.log('Bash script exported successfully:', path)
      }
    } catch (e) {
      console.error('Failed to export Bash script', e)
      alert('Failed to export Bash script')
    } finally {
      setIsExportingBash(false)
      onClose()
    }
  }

  return (
    <div className="bg-brand-surface/90 backdrop-blur-md border border-brand-border p-4 rounded-2xl flex flex-col gap-6 shadow-2xl text-brand-text min-w-[320px]">
      <div className="flex flex-col gap-1 border-b border-brand-border pb-3">
        <h3 className="text-xs font-bold uppercase tracking-widest text-brand-primary">Export Sprite</h3>
        <p className="text-[10px] text-brand-text/40">Choose an export format</p>
      </div>

      <div className="flex flex-col gap-3">
        <button 
          onClick={handleExportGif}
          disabled={isExportingGif || isExportingBash}
          className={`flex items-center gap-4 bg-brand-bg/50 p-4 rounded-xl border border-brand-border/30 transition-all group text-left ${
            isExportingGif ? 'opacity-50 cursor-not-allowed' : 'hover:border-brand-primary/50 hover:bg-brand-primary/5'
          }`}
        >
          <div className="w-10 h-10 bg-brand-primary/10 rounded-lg flex items-center justify-center text-brand-primary group-hover:scale-110 transition-transform shrink-0">
            {isExportingGif ? <Loader2 size={20} className="animate-spin" /> : <Download size={20} />}
          </div>
          <div className="flex flex-col">
            <span className="text-sm font-bold text-brand-text">
              {isExportingGif ? 'Exporting...' : 'Export as GIF'}
            </span>
            <span className="text-[10px] text-brand-text/70 mt-0.5 leading-tight">Animated image sequence of all frames</span>
          </div>
        </button>

        <button 
          onClick={handleExportBash}
          disabled={isExportingGif || isExportingBash}
          className={`flex items-center gap-4 bg-brand-bg/50 p-4 rounded-xl border border-brand-border/30 transition-all group text-left ${
            isExportingBash ? 'opacity-50 cursor-not-allowed' : 'hover:border-brand-primary/50 hover:bg-brand-primary/5'
          }`}
        >
          <div className="w-10 h-10 bg-brand-primary/10 rounded-lg flex items-center justify-center text-brand-primary group-hover:scale-110 transition-transform shrink-0">
            {isExportingBash ? <Loader2 size={20} className="animate-spin" /> : <Terminal size={20} />}
          </div>
          <div className="flex flex-col">
            <span className="text-sm font-bold text-brand-text">
              {isExportingBash ? 'Exporting...' : 'Export as Bash Script'}
            </span>
            <span className="text-[10px] text-brand-text/70 mt-0.5 leading-tight">Runnable script for terminal animation</span>
          </div>
        </button>

        <button 
          onClick={() => { alert('PNG + JSON export coming soon!'); onClose(); }}
          className="flex items-center gap-4 bg-brand-bg/50 p-4 rounded-xl border border-brand-border/30 hover:border-brand-primary/50 hover:bg-brand-primary/5 transition-all group text-left"
        >
          <div className="w-10 h-10 bg-brand-secondary/10 rounded-lg flex items-center justify-center text-brand-secondary group-hover:scale-110 transition-transform shrink-0">
            <FileImage size={20} />
          </div>
          <div className="flex flex-col">
            <span className="text-sm font-bold text-brand-text">Sprite Sheet</span>
            <span className="text-[10px] text-brand-text/70 mt-0.5 leading-tight">PNG + JSON coordinates for game engines</span>
          </div>
        </button>
      </div>
    </div>
  )
}

export default ExportModal
